services:
  frontend:
    build: ./frontend
    image: frontend

    ports:
      - "3000:3000"

    stdin_open: true
    tty: true

    depends_on:
      - backend

  backend:
    build: ./backend
    image: backend

    ports:
      - "5000:5000"

    env_file:
      - ./backend/.env

    environment:
      - QDRANT_URL=http://qdrant:6333
      - EMBEDDING_URL=http://embedding-service:8000/embed

    depends_on:
      - mongodb
      - qdrant
      - embedding-service

  embedding-service:
    build:
      context: ./backend/src/ai/embedding-service.py
      dockerfile: Dockerfile
    image: embedding-service
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - qdrant

  mongodb:
    image: mongo

    ports:
      - "27017:27017"

    volumes:
      - mongo-data:/data/db

  qdrant:
    image: qdrant/qdrant

    ports:
      - "6333:6333"
      - "6334:6334"

    volumes:
      - qdrant-data:/qdrant/storage

volumes:
  mongo-data:
  qdrant-data:
